apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Core components that enhance the functionality and reliability of the cluster.
  sourceRepos:
    - https://github.com/Jack-Gledhill/hydra-infra.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"