apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: cloudnative-pg
  url: https://cloudnative-pg.github.io/charts