apiVersion: v1
kind: Secret
metadata:
  name: jetstack
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: jetstack
  url: quay.io/jetstack
  enableOCI: "true"