apiVersion: v1
kind: Secret
metadata:
  name: metallb
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: metallb
  url: https://metallb.github.io/metallb