apiVersion: v1
kind: Secret
metadata:
  name: nfs-csi
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: nfs-csi
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts